version: "3.9"
services:
  neteaseapi:
    image: limeve/musicparty-neteaseapi:latest
    expose:
      - 3000
  qqmusicapi:
    image: limeve/musicparty-qqmusicapi:latest
    expose:
      - 3300
  frontend:
    image: limeve/musicparty-frontend:latest
    expose:
      - 3000
  backend:
    image: limeve/musicparty-backend:latest
    environment:
      MusicApi__NeteaseCloudMusic__Enabled: "true"
      MusicApi__NeteaseCloudMusic__ApiServerUrl: "http://neteaseapi:3000"
      MusicApi__NeteaseCloudMusic__PhoneNo: ""
      MusicApi__NeteaseCloudMusic__Cookie: ""
      MusicApi__QQMusic__Enabled: "true"
      MusicApi__QQMusic__ApiServerUrl: "http://qqmusicapi:3300"
      MusicApi__QQMusic__Cookie: ""
      MusicApi__Bilibili__Enabled: "true"
      MusicApi__Bilibili__SESSDATA: ""
      MusicApi__Bilibili__PhoneNo: ""
      FrontEndUrl: "http://frontend:3000"
    depends_on:
      - neteaseapi
      - qqmusicapi
    ports:
      - "2706:5000"
    tty: true
    restart: on-failure
